import type { KeywordLibrary } from './types';

/** English keyword library. */
export const en: KeywordLibrary = {
  language: 'en',
  categories: {
    weapon: {
      weight: 5,
      words: ['gun', 'knife', 'blade', 'weapon', 'pistol', 'firearm', 'rifle', 'machete', 'taser'],
      phrases: ['he has a gun', 'she has a knife', 'put the gun down', 'drop the knife'],
    },
    violence: {
      weight: 4,
      words: [
        'hit',
        'beat',
        'kill',
        'punch',
        'choke',
        'strangle',
        'slam',
        'attack',
        'smother',
        'kick',
        'slap',
        'stab',
        'shoot',
        'strike',
      ],
      phrases: ['beat me', 'kill you', 'kill me', "i'll kill", 'hold still'],
    },
    restraint: {
      weight: 3,
      words: ['stop', "don't", 'dont', 'release'],
      phrases: [
        "please don't",
        'please dont',
        'let me go',
        'let go',
        'stop it',
        'get off',
        'get off me',
        'leave me alone',
        "don't touch me",
        'stay back',
        'get away',
        'back off',
      ],
    },
    compliance: {
      weight: 2,
      words: [],
      phrases: [
        "i'll do whatever",
        "i'll do anything",
        'anything you want',
        'whatever you want',
        "i'll do what you say",
        "i won't tell",
        "i'll be quiet",
        'okay okay',
        "i'll cooperate",
      ],
    },
    fear: {
      weight: 3,
      words: ['help', 'scared', 'afraid', 'terrified', 'frightened'],
      phrases: [
        'help me',
        "don't hurt me",
        'dont hurt me',
        'hurt me',
        'please help',
        "i'm scared",
        'i am scared',
        'oh god',
        'get help',
        'call the police',
        'call 911',
        'somebody help',
        "don't kill me",
      ],
    },
    pain: {
      weight: 3,
      words: ['ow', 'ouch', 'hurts'],
      phrases: ['it hurts', "you're hurting me", 'youre hurting me', 'that hurts', "i'm hurt", 'my arm', 'my leg'],
    },
    medical: {
      weight: 4,
      words: ['bleeding', 'blood', 'breathe', 'dying', 'seizure', 'overdose', 'choking', 'unconscious'],
      phrases: [
        "can't breathe",
        'cant breathe',
        "i can't breathe",
        "i'm bleeding",
        "i'm dying",
        'heart attack',
        'not breathing',
        'losing blood',
      ],
    },
    disorientation: {
      weight: 2,
      words: ['dizzy', 'confused', 'drugged'],
      phrases: [
        'where am i',
        'what happened',
        "i can't see",
        'i feel dizzy',
        'what did you give me',
        "i can't think",
        'everything is spinning',
      ],
    },
    bargaining: {
      weight: 2,
      words: ['please'],
      phrases: [
        'i promise',
        'just let me',
        'please just',
        'please please',
        'we can talk',
        "let's talk",
        "i'll give you",
        'take the money',
        'take it',
        "i won't do it again",
      ],
    },
    // High-volume profanity reads as distress; the keyword layer flags it and
    // the tone layer (elevated-volume) corroborates. Casual profanity at
    // conversational volume will not carry the same weight in fusion.
    'profanity-distress': {
      weight: 2,
      words: ['fuck', 'shit', 'bastard', 'asshole'],
      phrases: ['fuck you', 'get the fuck', 'fucking stop', 'get off me you'],
    },
  },
};
