import { describe, expect, it } from 'vitest';

import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');

/**
 * The acceptance receipt is keyed on the Worker bundle hash, so that hash MUST be deterministic.
 *
 * It was not. `dist/README.md` is generated by wrangler and opens with "generated at
 * <ISO timestamp>", so two builds of byte-identical source hashed differently and the receipt
 * could never match anything — the mechanism built to save 1,481 metered requests saved none.
 *
 * A clock inside an identity makes the identity useless, and the failure is silent: nothing
 * errors, the gate simply always runs. This pins it.
 */
describe('the Worker bundle hash is deterministic', () => {
  it('two builds of identical source produce the same hash', () => {
    const hash = (): string =>
      execFileSync(process.execPath, [join(ROOT, 'scripts', 'worker-bundle-hash.mjs'), '--build'], {
        cwd: ROOT,
        encoding: 'utf8',
        stdio: ['ignore', 'pipe', 'ignore'],
      })
        .trim()
        .split(/\r?\n/)
        .pop()!
        .trim();

    const first = hash();
    expect(first, 'the hash is not a sha256').toMatch(/^[0-9a-f]{64}$/);
    expect(hash(), 'the Worker bundle hash is NOT deterministic — the receipt can never match').toBe(first);
  }, 180_000);
});
