#!/usr/bin/env node
/**
 * Brief 42 §A/§B — generate Cloudflare Pages `_headers` from the TRACKED policy.
 *
 * The policy lives in `config/security-headers.json` and is the input to two things: the audit
 * that proves it will not break the facade, and this generator that serves it. Writing the header
 * string by hand in a second place would mean the thing audited and the thing served could drift —
 * and the drift would be invisible, because each would look correct on its own.
 *
 * ═══ REPORT-ONLY IS THE DEFAULT ═══════════════════════════════════════════════════════════════
 *
 * §A: report-only first, over real use in both Present modes, then enforce. Never enforce blind —
 * a CSP that breaks the facade in Hidden is a covert-mode failure discovered by a survivor. So
 * this emits `Content-Security-Policy-Report-Only` unless `--enforce` is passed, and the flag is
 * recorded in the generated file so anyone reading `_headers` can see which mode is live.
 *
 * The §B transport and framing headers are emitted ENFORCED from the start. They are not
 * conditional on anything the app does: nosniff, a referrer policy, framing denial and a
 * permissions policy cannot break a render, and delaying them buys nothing.
 *
 * ═══ §E2 — NO REPORTING FIREHOSE ══════════════════════════════════════════════════════════════
 *
 * `report-uri`/`report-to` are deliberately NOT set. This Worker is metered, and an unbounded
 * violation-report endpoint is an attacker-controlled request generator pointed at the same plan
 * limit whose exhaustion takes the alert path down — the exact failure Brief 33 Fix A was written
 * about. Violations are collected from the browser console during a controlled pass instead,
 * which §E2 explicitly permits.
 *
 * Usage:  node scripts/build-headers.mjs [--enforce]
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const config = JSON.parse(readFileSync(path.join(ROOT, 'config/security-headers.json'), 'utf8'));
const enforce = process.argv.includes('--enforce');

/** Serialise the policy. Keys beginning with `_` are documentation, not directives. */
const policy = Object.entries(config.csp)
  .filter(([k]) => !k.startsWith('_'))
  .map(([directive, values]) => `${directive} ${values.join(' ')}`)
  .join('; ');

const headerLines = Object.entries(config.headers)
  .filter(([k]) => !k.startsWith('_'))
  .map(([name, value]) => `  ${name}: ${value}`);

const cspHeader = enforce ? 'Content-Security-Policy' : 'Content-Security-Policy-Report-Only';

const out = [
  '# GENERATED by scripts/build-headers.mjs from config/security-headers.json — do not edit.',
  '#',
  `# CSP mode: ${enforce ? 'ENFORCED' : 'REPORT-ONLY'}`,
  enforce
    ? '# Enforced after a report-only pass over both Present modes and a byte-identical facade diff.'
    : '# Report-only: violations are visible in the browser console and NOTHING is blocked.',
  '#',
  '# No report-uri/report-to by design (§E2): an unbounded violation endpoint on a metered Worker',
  '# is an attacker-controlled request generator pointed at the plan limit whose exhaustion takes',
  '# the alert path down. Violations are read from the console during a controlled pass.',
  '',
  '/*',
  `  ${cspHeader}: ${policy}`,
  ...headerLines,
  '',
].join('\n');

const target = path.join(ROOT, 'apps/pwa/public/_headers');
writeFileSync(target, out);
console.log(`_headers written (${enforce ? 'ENFORCED' : 'REPORT-ONLY'}) → ${path.relative(ROOT, target)}`);

// If a build already exists, keep it in step so an audit or deploy right now sees the same thing.
const dist = path.join(ROOT, 'apps/pwa/dist/_headers');
if (existsSync(path.join(ROOT, 'apps/pwa/dist'))) {
  writeFileSync(dist, out);
  console.log(`  and mirrored into the existing build → ${path.relative(ROOT, dist)}`);
}
